"""Rebuild the Volatility and Jump families from the derived specification, then
try to tell the rebuild apart from the feed.

`deriving.md` says `volatility_N_index` is driftless geometric Brownian motion
whose annualised volatility is exactly `N` percent, annualising at 365*24*60,
published every two seconds (the plain family) or every second (the `_1s`
twins). That is **two numbers per instrument**. This harness takes only those
two numbers, simulates ticks, aggregates them into one-minute bars with the
feed's own rule, and then runs the identical battery `genvol.py`, `fractal.py`
and `derivegbm.py` ran on the real feed.

The Jump family is the same exercise with an ambiguity in it.
`generators.md` measured 1.322x the name on all five and read it as a
convention - the name is the *diffusive* volatility and the jumps are extra,
leaving `1.322^2 - 1 = 0.7477` of the diffusive variance for them. The other
reading is that the diffusion itself runs at 1.322x and the jumps sit on top.
Those are different generators and they predict different kurtosis, so both are
built and the data is allowed to choose.

## What would count as failure, written before any number was looked at

1. **The volatility spec fails** if a rebuilt feed's realised annualised
   volatility lands outside the **0.5%** band `genvol.py` established against
   the name - the same bar the real feeds cleared, on all twelve.
2. **The Gaussian claim fails** if rebuilt 1m kurtosis is outside `3.00 +- 3
   SE` (`SE = sqrt(24/n)`, which is 0.0167 on 86,410 bars) or the
   structure-function Hurst exponent is outside `0.50 +- 0.01`, where the real
   feeds read 2.98-3.02 and 0.50.
3. **The tick model fails** if the rebuilt Parkinson-to-close ratio misses the
   real feed's by more than **1%**. This is the sharpest test on the page,
   because 0.870 and 0.909 are *not inputs* - they are what 30 and 60 ticks a
   bar produce, and `deriving.md` derives them from the 0.5826 constant to
   0.30%. A rebuild that gets the law right and the tick rate wrong fails here
   and nowhere else.
4. **The distributional claim fails** if a two-sample KS on 1m log returns,
   real against rebuilt, rejects at alpha = 0.05 on more than **3 of the 12**
   feeds. Twelve comparisons at a 5% test are expected to reject 0.6 times;
   three is the 99th percentile of Binomial(12, 0.05) and is the line.
5. **The independence claim fails** if the 66 pairwise correlations among the
   rebuilt feeds do not look like the 66 among the real feeds - specifically if
   the largest rebuilt |corr| exceeds the largest real one by more than the
   0.0068 two-standard-error band, or if the leading eigenvalue of the 12x12
   correlation matrix separates real from rebuilt.
6. **The run is void** if a statistic lands on *exactly* its null - kurtosis
   3.000000, a variance ratio of 1.000000, a correlation of 0.000000. This
   folder has published a dead column twice and it is a bug to hunt, not a
   match.
7. **The run is void** if the positive controls do not fire. A generator with
   sigma set 1% wrong, and one with Student-t(6) returns at matched variance,
   are put through the identical battery. If the battery cannot see a
   deliberately wrong generator then it cannot certify a right one, and nothing
   below is evidence.


## Amended before the real data was touched, and why

Every harness here was first run end to end against a **synthetic** database -
sixty days of bars and twenty-four hours of ticks for all twenty-six feeds,
generated by these same generators - so that a crash or a broken test would
surface on data whose truth was known rather than on the lab. Three conditions
were rewritten during that dry run. Each amendment is recorded here rather than
quietly applied, because a failure condition edited after seeing the answer is
not a failure condition, and the only defence is to say exactly when it was
edited and what forced it.

* **The positive controls were widened from two to seven.** Student-t(6) at
  matched tick variance turned out to be nearly invisible in *bar* returns - a
  bar is thirty or sixty ticks and the central limit theorem gets there first -
  so each wrong generator is now scored across the whole battery and counted as
  caught if any test sees it. Two rungs were added that test claims nothing else
  does: **half the tick rate** at the same volatility, which only the Parkinson
  ratio can see, and a **two-state volatility** at the same average variance,
  which only the clustering test can see. The VOID condition still names the two
  generators it originally named.
* **A resolution ladder** (sigma +1%, +0.5%, +0.2%) was added and is explicitly
  *not* required to be caught. Its job is to say where the battery runs out.

## The tick-monitored barrier, predicted before it is measured

`deriving.md` section one's whole table is **close-monitored**: `derivegbm.py`
walks non-overlapping windows on one-minute closes, so `P(up) = (b+B)/(a+b+2B)`
and `E[tau] = (a+B)(b+B)` are the answers for a rule that can only act once a
minute. **A real stop is hit on a tick.** The correction scales as
`beta * sigma * sqrt(dt)`, so at `tpb` ticks a minute the shift in one-minute
sigmas falls from 0.5826 to `0.5826 / sqrt(tpb)` - **0.1064** at 30 ticks a bar
and **0.0752** at 60 - and the trading-relevant hit probability sits *between*
the continuous answer and the published one.

Written down before any of it was run, at a 3:1 stop-to-target:

| | continuous | close-monitored (published) | **tick-monitored (predicted)** |
| --- | --- | --- | --- |
| 3:1, 30 ticks a bar | 0.2500 | 0.3073 measured / 0.3064 derived | **0.2626** |
| 3:1, 60 ticks a bar | 0.2500 | 0.3073 / 0.3064 | **0.2591** |
| 1:3, 30 ticks a bar | 0.7500 | 0.6928 / 0.6936 | **0.7374** |
| 2:10, 30 ticks a bar | 0.8333 | 0.8042 / 0.8038 | **0.8275** |

That is a number this desk sizes on and does not have: a 1:3 barrier is a 25.0%
shot continuously, a 30.7% shot to a rule that checks once a minute, and a
**26.3%** shot to a stop that sits in the book. The published figure overstates
it by four points.

**It fails** if the measured tick-monitored `P(up)` is outside 0.005 of the
prediction on the rebuilt paths, or if the real tick table - 43,000 to 86,400
ticks a feed, about 400 non-overlapping 3:1 trades each, 5,000 pooled - puts it
more than 3 standard errors away. The gap between the close-monitored and
tick-monitored values is 0.045, which is 6.3 standard errors at that count, so
the sample resolves it; if it did not, that would be said instead.

## The controls

* **real against real** - the first thirty days against the last thirty, through
  the same tests. Whatever that produces is the floor; a rebuild that does no
  worse is indistinguishable in the only sense this sample can support.
* **sigma + 1%** and **Student-t(6)** as deliberately wrong generators.
* **across seeds** - every headline number is reported as a mean and a spread
  over `SEEDS` independent seeds, against the real feed's own standard error.
  A rebuild whose seed-to-seed spread is comparable to the real standard error
  has not been tested; the Monte Carlo has to be the sharper instrument.
"""

from __future__ import annotations

import json
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rebuildgen as G

OUT = os.environ.get("OUT", os.path.expanduser("~/till_infinity/logs/rebuildvol.json"))
SEEDS = [int(s) for s in os.environ.get("SEEDS", "20260912,20260913,20260914,20260915").split(",")]
#: How many times the real sample the Monte Carlo runs. Requirement one of the
#: brief: the simulation has to be the sharper instrument, not the blunter one.
MULT = int(os.environ.get("MULT", "10"))
JMULT = int(os.environ.get("JMULT", "4"))
#: Ticks retained from the first seed's rebuild. The tick-return KS needs only as
#: many as the feed has; the tick-monitored barrier needs enough trades to resolve
#: a 0.045 gap, which is a few hundred thousand.
TICK_KEEP = int(os.environ.get("TICK_KEEP", "2000000"))
#: How a continuous price is put onto the venue's quote lattice, which is the
#: whole of `rebuildladder.py`'s ladder. One of "price" (round the accumulated
#: price - refuted by P(0)), "bump" (round the increment and move one unit on a
#: zero - refuted by the one-unit bin), "resample" (round the increment and
#: redraw until the quote changes) or the default "drop" (round the price, build
#: the bars from every tick, and delete the repeated quotes from the tick stream
#: only). "0"/"1" still name the first two.
#:
#: `drop` rather than `resample` because they have the same tick law and
#: different bars. `resample` raises the per-tick second moment by 1/(1-P(0)) -
#: 1.5% of sigma on volatility_100_index, against a pre-registered volatility
#: band of 0.5% - where `drop` leaves the bars exactly as the venue builds them,
#: from its own complete stream including the quotes it repeats.
LATTICE = {"0": "price", "false": "price", "": "price", "1": "bump",
           "true": "bump"}.get(os.environ.get("LATTICE", "drop").lower(),
                               os.environ.get("LATTICE", "drop"))

NOMINAL = {
    "volatility_10_index": 10.0, "volatility_25_index": 25.0,
    "volatility_50_index": 50.0, "volatility_75_index": 75.0,
    "volatility_100_index": 100.0,
    "volatility_10_1s_index": 10.0, "volatility_25_1s_index": 25.0,
    "volatility_50_1s_index": 50.0, "volatility_75_1s_index": 75.0,
    "volatility_100_1s_index": 100.0, "volatility_150_1s_index": 150.0,
    # `generators.md` records that this one has zero bars in research.db and is
    # the only member of the family never tested. It is listed so the absence is
    # printed rather than quietly dropped.
    "volatility_200_1s_index": 200.0,
    "volatility_250_1s_index": 250.0,
}
JUMP_NOMINAL = {"jump_10_index": 10.0, "jump_25_index": 25.0, "jump_50_index": 50.0,
                "jump_75_index": 75.0, "jump_100_index": 100.0}
#: The published tick rate: 0.5/s for the plain family, 1/s for the `_1s` twins.
#: These are the *generator's* rate, so the bar count per minute is 30 and 60 -
#: our tick capture drops some ticks on some feeds but the venue's bars are not
#: built from our capture, and `derivegbm.py`'s Parkinson table confirms it.
def ticks_per_bar(feed: str) -> int:
    return 60 if "_1s_" in feed else 30


#: The measured multiplier. `generators.md`: five feeds, mean 1.3226.
JUMP_MULT = 1.3226
PAIRS = [(5, 5), (3, 1), (2, 10)]


def two_barrier(logp: np.ndarray, a: float, b: float, u: float) -> dict:
    """`derivegbm.py`'s non-overlapping barrier replay, monitoring at the close."""
    n = logp.size
    i, ups = 0, 0
    taus = []
    while i < n - 1:
        x0 = logp[i]
        j = i + 1
        hit = 0
        while j < n:
            d = (logp[j] - x0) / u
            if d >= a:
                hit = 1
                break
            if d <= -b:
                hit = -1
                break
            j += 1
        if hit == 0:
            break
        ups += 1 if hit > 0 else 0
        taus.append(j - i)
        i = j
    if not taus:
        return {"n": 0}
    t = np.array(taus, dtype=float)
    return {"n": len(taus), "p_up": ups / len(taus), "etau": float(t.mean()),
            "se_p": math.sqrt(0.25 / len(taus))}


def tick_barrier(logp: np.ndarray, a: float, b: float, u: float,
                 cap: int = 3_000_000) -> tuple[float, int]:
    """The same non-overlapping barrier replay, monitored on every tick.

    A list is used rather than a numpy array because the scan is inherently
    sequential and Python list indexing is about three times faster than numpy
    scalar indexing; at three million ticks that is the difference between
    seconds and a minute.
    """
    x = (np.asarray(logp[:cap], dtype=float) / u).tolist()
    n = len(x)
    i, ups, taus = 0, 0, 0
    while i < n - 1:
        x0 = x[i]
        j = i + 1
        hit = 0
        while j < n:
            d = x[j] - x0
            if d >= a:
                hit = 1
                break
            if d <= -b:
                hit = -1
                break
            j += 1
        if hit == 0:
            break
        ups += 1 if hit > 0 else 0
        taus += 1
        i = j
    return (ups / taus if taus else float("nan")), taus


def battery(ts, _open, h, lo, cl, nominal, ticks=None, keep_rets=True) -> dict:
    r = G.logrets(cl, ts)
    got = {
        "n_bars": int(cl.size), "n_rets": int(r.size),
        "ann_vol": G.ann_vol(r), "ann_vol_se": G.ann_vol_se(r),
        "kurtosis": G.kurtosis(r), "kurtosis_se": G.kurtosis_se(r.size),
        "skew": float((((r - r.mean()) / r.std(ddof=0)) ** 3).mean()),
        "parkinson_ratio": G.parkinson_ratio(h, lo, cl),
        "acf_ret": {lg: G.acf(r, lg) for lg in G.LAGS},
        "acf_abs": {lg: G.acf(np.abs(r), lg) for lg in G.LAGS},
        "vr": {q: G.variance_ratio(r, q) for q in G.VR_Q},
        "vr_se": {q: G.variance_ratio_se(r, q) for q in G.VR_Q},
        # The sign sequence, tested the way `genstep.py` tests Step Index's: a
        # runs test catches alternation and persistence that a linear
        # autocorrelation on the returns themselves can miss.
        "sign_acf1": G.acf(np.sign(r), 1),
        "sign_band": 3.0 / math.sqrt(r.size),
        "runs_z": G.runs_z(np.sign(r)),
        "p_up": float((r > 0).mean()),
        "p_up_se": math.sqrt(0.25 / r.size),
        "mean_ret": float(r.mean()), "mean_ret_se": float(r.std(ddof=1) / math.sqrt(r.size)),
    }
    got["ratio_to_name"] = got["ann_vol"] / nominal
    got.update(G.hurst(ts, cl))
    u = (nominal / 100.0) / math.sqrt(G.MINUTES_PER_YEAR)
    # The barrier replay is a scan in Python, so it is capped at 300,000 bars -
    # 3.5x the real sample, which is already the sharper side of the comparison.
    lg = np.log(cl[:300_000])
    got["barrier"] = {f"{a}:{b}": two_barrier(lg, a, b, u) for a, b in PAIRS}
    if keep_rets:
        got["_rets"] = r
    if ticks is not None and ticks.size > 100:
        tr = np.diff(np.log(ticks))
        got["_tickrets"] = tr[np.isfinite(tr)]
    return got


def simulate_vol(feed, nominal, p0, grid, n_bars, seed, keep_ticks=0, sigma_mult=1.0,
                 student_df=0, tpb_override=0, cluster=False, lattice=LATTICE):
    tpb = tpb_override or ticks_per_bar(feed)
    # The seed is (run seed, feed) rather than the run seed alone. Seeding every
    # feed identically would hand all twelve rebuilds the same Gaussian draws
    # scaled by sigma, which makes the twelve comparisons one comparison and
    # produces byte-identical variance ratios down the column. That is the
    # dead-column failure in a new costume, and the first version of this
    # harness did it.
    rng = np.random.default_rng([int(seed), G.feed_seed(feed)])
    tick_s = 60.0 / tpb
    # `drop` is not a quantiser, it is an *observation* rule: the stream is the
    # price-rounded one - which is what the venue's own bars are built from - and
    # the repeated quotes are deleted from the ticks afterwards, which is what
    # our collector does. It therefore applies to the deliberately wrong
    # generators identically, and the over-collection is because the deletion
    # shortens the tick stream.
    dedup = lattice == "drop"
    mode = "price" if dedup else lattice
    want = int(keep_ticks * 1.6) if (dedup and keep_ticks) else keep_ticks
    if student_df:
        stream = _student_stream(n_bars * tpb, nominal * sigma_mult, tick_s, p0, grid,
                                 rng, student_df, lattice=mode)
    elif cluster:
        stream = _cluster_stream(n_bars * tpb, nominal * sigma_mult, tick_s, p0, grid,
                                 rng, tpb, lattice=mode)
    else:
        stream = G.gen_gbm(n_bars * tpb, nominal * sigma_mult, tick_s, p0, grid, rng,
                           lattice=mode)
    out = G.bars_from_stream(stream, tpb, n_bars, keep_ticks=want)
    if dedup and out["ticks"].size:
        tk = out["ticks"]
        out["ticks"] = tk[np.concatenate([[True], np.diff(tk) != 0])][:keep_ticks]
    return out


def _cluster_stream(n_ticks, sigma_ann, tick_seconds, p0, grid, rng, tpb,
                    block_bars=60, lo=0.7, hi=1.3, lattice=LATTICE):
    """The other deliberately wrong generator: the same average variance, but it
    alternates between two volatility states in hour-long blocks.

    This is what every real market does and no Deriv synthetic does
    (`generators.md`: largest |acf| of |return| across 26 synthetics is 0.017
    against gold's 0.219). It exists to prove the clustering test has power.
    """
    mode = G.lattice_mode(lattice)
    base = (sigma_ann / 100.0) * math.sqrt(tick_seconds / G.SECONDS_PER_YEAR)
    scale = base / math.sqrt((lo ** 2 + hi ** 2) / 2.0)
    blk = block_bars * tpb
    logp = math.log(p0)
    price = p0
    done = 0
    state = 0
    while done < n_ticks:
        m = min(blk, n_ticks - done)
        mult = lo if state == 0 else hi
        state = 1 - state
        path = logp + np.cumsum(rng.standard_normal(m) * scale * mult)
        logp = float(path[-1])
        px = np.exp(path)
        # the same quantiser as the honest rebuild: a control that differs in the
        # law *and* in the lattice rule cannot say which of the two was caught
        out = G.lattice_walk(px, price, grid, mode, scale * mult, rng)
        price = float(out[-1])
        yield out
        done += m


def _student_stream(n_ticks, sigma_ann, tick_seconds, p0, grid, rng, df, chunk=2_000_000,
                    lattice=LATTICE):
    """The deliberately wrong generator: Student-t tick innovations rescaled to
    the same per-tick variance. Same volatility, same martingale, wrong law."""
    mode = G.lattice_mode(lattice)
    sigma_tick = (sigma_ann / 100.0) * math.sqrt(tick_seconds / G.SECONDS_PER_YEAR)
    scale = sigma_tick / math.sqrt(df / (df - 2.0))
    logp = math.log(p0)
    price = p0
    done = 0
    while done < n_ticks:
        m = min(chunk, n_ticks - done)
        path = logp + np.cumsum(rng.standard_t(df, m) * scale)
        logp = float(path[-1])
        px = np.exp(path)
        out = G.lattice_walk(px, price, grid, mode, sigma_tick, rng)
        price = float(out[-1])
        yield out
        done += m


def main() -> None:
    rng = np.random.default_rng(90210)
    ledger: list[dict] = []
    payload: dict = {"seeds": SEEDS, "mult": MULT}
    print("=" * 120)
    print("REBUILDING THE VOLATILITY AND JUMP FAMILIES FROM THE DERIVED SPECIFICATION")
    print(f"  seeds {SEEDS}   simulation = {MULT}x the real sample   {G.machine()}")
    print("=" * 120)

    real: dict = {}
    print("\n[0] THE REAL FEED, and the two numbers the rebuild is allowed to know")
    print(f"{'feed':26s} {'bars':>7s} {'ticks/s':>8s} {'spec tpb':>9s} {'grid':>10s} "
          f"{'p0':>12s} {'ann vol':>9s} {'+-SE':>7s} {'name':>6s}")
    for feed, nom in NOMINAL.items():
        b = G.real_bars(feed)
        t = G.real_ticks(feed)
        if not b.get("n") or not t.get("n"):
            print(f"{feed:26s}  absent from research.db - skipped")
            continue
        grid = G.quote_grid(t["mid"])
        st = battery(b["ts"], b["open"], b["high"], b["low"], b["close"], nom)
        st["grid"] = grid
        st["per_sec"] = t["per_sec"]
        st["p0"] = float(b["close"][0])
        tr = np.diff(np.log(t["mid"]))
        st["_tickrets"] = tr[np.isfinite(tr)]
        st["open_is_prev_close"] = float(np.mean(b["open"][1:] == b["close"][:-1]))
        st["_close"], st["_ts"] = b["close"], b["ts"]
        real[feed] = st
        print(f"{feed:26s} {st['n_bars']:7d} {t['per_sec']:8.4f} {ticks_per_bar(feed):9d} "
              f"{grid:10.6g} {st['p0']:12.4f} {st['ann_vol']:9.3f} {st['ann_vol_se']:7.3f} "
              f"{nom:6.0f}")
    print("\n    bar open equals the previous close on: " + ", ".join(
        f"{f.split('_')[1]}={real[f]['open_is_prev_close']:.3f}" for f in list(real)[:6]))
    print("    (0.000 confirms the bar's range is over its own ticks only - the convention"
          "\n     `derivegbm.py` found the Parkinson ratio matches)")

    # ------------------------------------------------------------------ rebuild
    print(f"\n[1] THE REBUILD - realised volatility, {len(SEEDS)} seeds, "
          f"{MULT}x the real sample each")
    print(f"{'feed':26s} {'name':>6s} {'real':>9s} {'real SE':>8s} | {'sim mean':>9s} "
          f"{'sim sd':>8s} {'sim min':>9s} {'sim max':>9s} {'ratio':>7s} {'band 0.5%':>10s}")
    sims: dict[str, list[dict]] = {}
    for feed, nom in NOMINAL.items():
        if feed not in real:
            continue
        n_bars = min(real[feed]["n_bars"] * MULT, 1_200_000)
        runs = []
        for k, sd in enumerate(SEEDS):
            bb = simulate_vol(feed, nom, real[feed]["p0"], real[feed]["grid"], n_bars,
                              sd, keep_ticks=TICK_KEEP if k == 0 else 0)
            st = battery(bb["ts"], bb["open"], bb["high"], bb["low"], bb["close"], nom,
                         ticks=bb["ticks"] if k == 0 else None, keep_rets=(k == 0))
            if k == 0:
                st["_ticks_long"] = bb["ticks"]
            runs.append(st)
        sims[feed] = runs
        sp = G.spread_across([r["ann_vol"] for r in runs])
        ratio = sp["mean"] / nom
        ok = abs(ratio - 1.0) <= 0.005
        print(f"{feed:26s} {nom:6.0f} {real[feed]['ann_vol']:9.3f} "
              f"{real[feed]['ann_vol_se']:8.3f} | {sp['mean']:9.3f} {sp['sd']:8.4f} "
              f"{sp['min']:9.3f} {sp['max']:9.3f} {ratio:7.4f} "
              f"{'pass' if ok else 'FAIL':>10s}", flush=True)
        ledger.append({"test": "realised vol within 0.5% of the name", "feed": feed,
                       "value": ratio, "fired": not ok})

    print("\n[2] KURTOSIS, HURST AND THE PARKINSON RATIO - none of the three is an input")
    print(f"{'feed':26s} {'kurt real':>9s} {'kurt sim':>9s} {'+-sd':>7s} {'SE':>6s} "
          f"{'H real':>7s} {'H sim':>7s} {'park real':>10s} {'park sim':>9s} {'err':>8s}")
    for feed, rr in sims.items():
        rl = real[feed]
        ks_ = G.spread_across([r["kurtosis"] for r in rr])
        hs = G.spread_across([r["H"] for r in rr])
        ps = G.spread_across([r["parkinson_ratio"] for r in rr])
        perr = ps["mean"] / rl["parkinson_ratio"] - 1.0
        print(f"{feed:26s} {rl['kurtosis']:9.4f} {ks_['mean']:9.4f} {ks_['sd']:7.4f} "
              f"{rl['kurtosis_se']:6.4f} {rl['H']:7.4f} {hs['mean']:7.4f} "
              f"{rl['parkinson_ratio']:10.4f} {ps['mean']:9.4f} {100 * perr:7.2f}%")
        ledger.append({"test": "kurtosis within 3 SE of 3.00", "feed": feed,
                       "value": ks_["mean"],
                       "fired": abs(ks_["mean"] - 3.0) > 3 * rl["kurtosis_se"]})
        ledger.append({"test": "Hurst within 0.01 of 0.50", "feed": feed,
                       "value": hs["mean"], "fired": abs(hs["mean"] - 0.5) > 0.01})
        ledger.append({"test": "Parkinson ratio within 1% of the feed", "feed": feed,
                       "value": perr, "fired": abs(perr) > 0.01})
        if G.exactly_null(ks_["mean"], 3.0) or G.exactly_null(hs["mean"], 0.5):
            ledger.append({"test": "VOID: statistic on exactly its null", "feed": feed,
                           "value": ks_["mean"], "fired": True})

    print("\n    the 0.870 / 0.909 that `deriving.md` derives from BETA = 0.5826, and that"
          "\n    the rebuild was never told:")
    for tpb, want in ((30, 0.870), (60, 0.909)):
        vals = [G.spread_across([r["parkinson_ratio"] for r in sims[f]])["mean"]
                for f in sims if ticks_per_bar(f) == tpb]
        rvals = [real[f]["parkinson_ratio"] for f in sims if ticks_per_bar(f) == tpb]
        if vals:
            print(f"      {tpb} ticks/bar: rebuilt {np.mean(vals):.4f}  real {np.mean(rvals):.4f}"
                  f"  generators.md {want:.3f}  BGK first order "
                  f"{1 - 2 * G.BETA / math.sqrt(8 * tpb / math.pi):.4f}")

    print("\n[3a] THE SIGN SEQUENCE - runs test and sign autocorrelation, feed against rebuild")
    print(f"{'feed':26s} {'p(up) feed':>11s} {'rebuilt':>9s} {'+-SE':>8s} | "
          f"{'signACF feed':>13s} {'rebuilt':>9s} {'band':>8s} | {'runs z feed':>12s} "
          f"{'rebuilt':>9s}")
    for feed, rr in sims.items():
        rl = real[feed]
        pu = G.spread_across([r["p_up"] for r in rr])
        sa = G.spread_across([r["sign_acf1"] for r in rr])
        rz = G.spread_across([r["runs_z"] for r in rr])
        print(f"{feed:26s} {rl['p_up']:11.5f} {pu['mean']:9.5f} {rl['p_up_se']:8.5f} | "
              f"{rl['sign_acf1']:+13.5f} {sa['mean']:+9.5f} {rl['sign_band']:8.5f} | "
              f"{rl['runs_z']:+12.3f} {rz['mean']:+9.3f}")
        ledger.append({"test": "rebuilt sign acf inside +-3/sqrt(n)", "feed": feed,
                       "value": sa["mean"], "fired": abs(sa["mean"]) > rl["sign_band"]})
        ledger.append({"test": "rebuilt |runs z| <= 3", "feed": feed, "value": rz["mean"],
                       "fired": abs(rz["mean"]) > 3})
        ledger.append({"test": "rebuilt p(up) within 3 SE of 0.5", "feed": feed,
                       "value": (pu["mean"] - 0.5) / rl["p_up_se"],
                       "fired": abs(pu["mean"] - 0.5) > 3 * rl["p_up_se"]})

    print("\n[3] VARIANCE RATIOS AND AUTOCORRELATION - martingale, and no clustering")
    print(f"{'feed':26s} " + " ".join(f"{'VRq' + str(q):>9s}" for q in G.VR_Q)
          + f" {'acf|r|1 real':>13s} {'sim':>9s}")
    for feed, rr in sims.items():
        row = [G.spread_across([r["vr"][q] for r in rr])["mean"] for q in G.VR_Q]
        a1 = G.spread_across([r["acf_abs"][1] for r in rr])["mean"]
        print(f"{feed:26s} " + " ".join(f"{v:9.5f}" for v in row)
              + f" {real[feed]['acf_abs'][1]:13.5f} {a1:9.5f}")
        for q, v in zip(G.VR_Q, row, strict=False):
            se = real[feed]["vr_se"][q]
            ledger.append({"test": f"variance ratio q={q} within 3 SE of 1", "feed": feed,
                           "value": v, "fired": abs(v - 1.0) > 3 * se})
        if any(G.exactly_null(v, 1.0) for v in row):
            ledger.append({"test": "VOID: variance ratio exactly 1.000000", "feed": feed,
                           "value": row[0], "fired": True})

    # ------------------------------------------------- distributional tests ---
    print("\n[4] DISTRIBUTION, NOT MOMENTS - two-sample KS / AD / chi-square on 1m log returns")
    print("    real against rebuilt (seed 1), and real-first-half against real-last-half as")
    print("    the floor. D_crit is the 5% critical value at these sample sizes.")
    print(f"{'feed':26s} {'n real':>8s} {'n sim':>9s} {'KS D':>9s} {'D crit':>8s} {'KS p':>8s} "
          f"{'AD p':>8s} {'chi2 p':>8s} {'n* (KS)':>12s} | {'D real/real':>11s}")
    for feed in sims:
        a = real[feed]["_rets"]
        b = sims[feed][0]["_rets"]
        k = G.ks2(a, b, rng=rng)
        ad = G.ad2(a, b, rng=rng)
        c2 = G.chi2_hist(a, b)
        h = a.size // 2
        kc = G.ks2(a[:h], a[h:], rng=rng)
        ns = G.nstar(k["D"])
        print(f"{feed:26s} {a.size:8d} {b.size:9d} {k['D']:9.5f} {k['D_crit_05']:8.5f} "
              f"{k['p']:8.4f} {ad['p']:8.4f} {c2['p']:8.4f} {ns:12.3g} | {kc['D']:11.5f}")
        ledger.append({"test": "KS on 1m log returns does not reject", "feed": feed,
                       "value": k["p"], "fired": k["reject"]})
        payload.setdefault("ks_bars", {})[feed] = {"ks": k, "ad": ad, "chi2": c2,
                                                   "control": kc, "nstar": ns}

    print("\n[5] THE SAME TESTS ON TICK RETURNS - where the quote grid lives")
    print(f"{'feed':26s} {'n real':>8s} {'n sim':>9s} {'KS D':>9s} {'D crit':>8s} {'KS p':>8s} "
          f"{'chi2 p':>8s} {'n* (KS)':>12s}")
    for feed in sims:
        a = real[feed]["_tickrets"]
        b = sims[feed][0].get("_tickrets")
        if b is None or b.size < 1000:
            continue
        k = G.ks2(a, b, rng=rng)
        c2 = G.chi2_hist(a, b)
        print(f"{feed:26s} {a.size:8d} {b.size:9d} {k['D']:9.5f} {k['D_crit_05']:8.5f} "
              f"{k['p']:8.4f} {c2['p']:8.4f} {G.nstar(k['D']):12.3g}")
        payload.setdefault("ks_ticks", {})[feed] = {"ks": k, "chi2": c2,
                                                    "nstar": G.nstar(k["D"])}
        ledger.append({"test": "KS on tick returns does not reject", "feed": feed,
                       "value": k["p"], "fired": k["reject"]})

    print("\n[6] THE TAILS, QUANTILE BY QUANTILE - volatility_75_index, in 1m sigmas")
    f = "volatility_75_index" if "volatility_75_index" in sims else next(iter(sims))
    u = (NOMINAL[f] / 100.0) / math.sqrt(G.MINUTES_PER_YEAR)
    print(f"{'p':>8s} {'real':>10s} {'rebuilt':>10s} {'ratio':>8s} {'normal':>10s}")
    from scipy.stats import norm
    for row in G.qq(real[f]["_rets"] / u, sims[f][0]["_rets"] / u):
        rs = "-" if math.isnan(row["ratio"]) else f"{row['ratio']:.4f}"
        print(f"{row['p']:8.4f} {row['real']:10.4f} {row['sim']:10.4f} {rs:>8s} "
              f"{norm.ppf(row['p']):10.4f}")

    # ------------------------------------------------------- positive controls --
    print("\n[7] THE POSITIVE CONTROLS - can this battery see a generator that is wrong?")
    print("    If it cannot, nothing above is evidence. Five deliberately wrong generators,")
    print("    each through the whole battery rather than through one test, because the")
    print("    tests have very different power and a wrong generator only has to be caught")
    print("    once. `volatility_75_index`, at the real sample's own size.")
    print(f"{'wrong generator':32s} {'vol z':>8s} {'kurt z':>8s} {'park err':>9s} "
          f"{'acf|r|1 z':>10s} {'bar KS p':>9s} {'tick KS p':>10s} {'caught by':>22s}")
    ctl = {}
    nb_ctl = real[f]["n_bars"]
    nt_ctl = real[f]["_tickrets"].size + 1
    rl = real[f]
    for name, kw in (("sigma exact (the rebuild)", {}),
                     ("sigma +1%", {"sigma_mult": 1.01}),
                     ("sigma +0.5%", {"sigma_mult": 1.005}),
                     ("sigma +0.2%", {"sigma_mult": 1.002}),
                     ("Student-t(6), matched var", {"student_df": 6}),
                     ("half the tick rate", {"tpb_override": 15}),
                     ("vol clustering, same mean var", {"cluster": True})):
        bb = simulate_vol(f, NOMINAL[f], rl["p0"], rl["grid"], nb_ctl, SEEDS[0] + 7,
                          keep_ticks=nt_ctl, **kw)
        r2 = G.logrets(bb["close"], bb["ts"])
        tr2 = np.diff(np.log(bb["ticks"]))
        tr2 = tr2[np.isfinite(tr2)]
        volz = (G.ann_vol(r2) - rl["ann_vol"]) / rl["ann_vol_se"]
        kz = (G.kurtosis(r2) - rl["kurtosis"]) / rl["kurtosis_se"]
        pk = G.parkinson_ratio(bb["high"], bb["low"], bb["close"])
        perr = pk / rl["parkinson_ratio"] - 1.0
        a1 = G.acf(np.abs(r2), 1)
        az = a1 * math.sqrt(r2.size)
        kb = G.ks2(rl["_rets"], r2, rng=rng)
        kt = G.ks2(rl["_tickrets"], tr2, rng=rng)
        caught = []
        if abs(volz) > 3:
            caught.append("vol")
        if abs(kz) > 3:
            caught.append("kurt")
        if abs(perr) > 0.01:
            caught.append("park")
        if abs(az) > 3:
            caught.append("acf")
        if kb["reject"]:
            caught.append("barKS")
        if kt["reject"]:
            caught.append("tickKS")
        tag = ",".join(caught) if caught else "NOTHING"
        print(f"{name:32s} {volz:+8.2f} {kz:+8.2f} {100 * perr:8.2f}% {az:+10.2f} "
              f"{kb['p']:9.4f} {kt['p']:10.4f} {tag:>22s}")
        ctl[name] = {"vol_z": volz, "kurt_z": kz, "park_err": perr, "acf_z": az,
                     "bar_ks": kb, "tick_ks": kt, "caught": caught}
    payload["controls"] = ctl
    # The pre-registered condition names two generators: sigma 1% wrong and
    # Student-t(6). The 0.5% and 0.2% rungs were added to map where the battery
    # runs out of resolution and are *not* required to be caught - a miss there
    # is the measurement, not a failure.
    named = ["sigma +1%", "Student-t(6), matched var"]
    missed = [n for n in named if not ctl[n]["caught"]]
    ledger.append({"test": "VOID unless the named wrong generators are caught",
                   "feed": ", ".join(missed) if missed else "none missed",
                   "value": float(len(missed)), "fired": bool(missed)})
    extra = [n for n, v in ctl.items()
             if n not in named and n != "sigma exact (the rebuild)" and not v["caught"]]
    print(f"    resolution: the battery caught everything except {extra or 'nothing'}")
    honest = ctl["sigma exact (the rebuild)"]["caught"]
    ledger.append({"test": "the honest rebuild is not caught by the same battery",
                   "feed": ",".join(honest) if honest else "clean",
                   "value": float(len(honest)), "fired": bool(honest)})

    # ------------------------------------------------------ parameter recovery --
    print("\n[8] THE REVERSE DIRECTION - fit the rebuild's own output back with the")
    print("    estimators used on the real feeds, and see whether they recover the input.")
    print(f"{'feed':26s} {'sigma in':>9s} {'sigma out':>10s} {'z':>7s} {'H out':>7s} "
          f"{'kurt out':>9s} {'drift z':>8s}")
    for feed, rr in sims.items():
        sp = G.spread_across([r["ann_vol"] for r in rr])
        se = G.spread_across([r["ann_vol_se"] for r in rr])["mean"]
        z = (sp["mean"] - NOMINAL[feed]) / se if se else float("nan")
        dz = G.spread_across([r["mean_ret"] / r["mean_ret_se"] for r in rr])["mean"]
        print(f"{feed:26s} {NOMINAL[feed]:9.1f} {sp['mean']:10.4f} {z:7.2f} "
              f"{G.spread_across([r['H'] for r in rr])['mean']:7.4f} "
              f"{G.spread_across([r['kurtosis'] for r in rr])['mean']:9.4f} {dz:8.2f}")
        ledger.append({"test": "recovered sigma within 3 SE of the input", "feed": feed,
                       "value": z, "fired": abs(z) > 3})

    # ----------------------------------------------------- BGK closed forms ----
    print("\n[9] THE 0.5826 CORRECTION, EMERGENT - barrier statistics off the rebuilt bars")
    print("    The rebuild was never told about BETA. If the corrected closed forms fit")
    print("    its output as well as they fit the feed, the constant is a property of the")
    print("    tick-and-aggregate construction rather than a patch on it.")
    print(f"{'a:b':>6s} {'P(up) real':>11s} {'P(up) sim':>10s} {'continuous':>11s} "
          f"{'corrected':>10s} | {'E[tau] real':>12s} {'sim':>9s} {'cont':>8s} {'corr':>8s}")
    for a, b in PAIRS:
        k = f"{a}:{b}"
        nr = sum(real[f2]["barrier"][k].get("n", 0) for f2 in sims)
        ns_ = sum(sims[f2][0]["barrier"][k].get("n", 0) for f2 in sims)
        if not nr or not ns_:
            continue
        pr = sum(real[f2]["barrier"][k].get("p_up", 0) * real[f2]["barrier"][k]["n"]
                 for f2 in sims) / nr
        ps = sum(sims[f2][0]["barrier"][k].get("p_up", 0) * sims[f2][0]["barrier"][k]["n"]
                 for f2 in sims) / ns_
        tr = sum(real[f2]["barrier"][k].get("etau", 0) * real[f2]["barrier"][k]["n"]
                 for f2 in sims) / nr
        tsx = sum(sims[f2][0]["barrier"][k].get("etau", 0) * sims[f2][0]["barrier"][k]["n"]
                  for f2 in sims) / ns_
        pc = b / (a + b)
        pd = (b + G.BETA) / (a + b + 2 * G.BETA)
        print(f"{k:>6s} {pr:11.4f} {ps:10.4f} {pc:11.4f} {pd:10.4f} | {tr:12.3f} "
              f"{tsx:9.3f} {a * b:8.3f} {(a + G.BETA) * (b + G.BETA):8.3f}")
        payload.setdefault("barrier", {})[k] = {"p_real": pr, "p_sim": ps, "p_cont": pc,
                                                "p_disc": pd, "t_real": tr, "t_sim": tsx}

    # ------------------------------------------- the tick-monitored barrier ---
    print("\n[9b] THE TICK-MONITORED BARRIER - what a stop in the book actually gets")
    print("     `deriving.md`'s table monitors at the close. A stop is hit on a tick, so")
    print("     the shift is BETA/sqrt(tpb) of a one-minute sigma rather than BETA.")
    print(f"{'feed':26s} {'tpb':>4s} {'a:b':>5s} {'P tick sim':>11s} {'n':>7s} "
          f"{'P tick real':>12s} {'n':>7s} {'predicted':>10s} {'close-mon':>10s} "
          f"{'continuous':>11s} {'z sim':>7s} {'z real':>7s}")
    tickrows = []
    for feed, nom in NOMINAL.items():
        if feed not in real:
            continue
        tpb = ticks_per_bar(feed)
        u = (nom / 100.0) / math.sqrt(G.MINUTES_PER_YEAR)
        bp = G.BETA / math.sqrt(tpb)
        rt = G.real_ticks(feed)
        real_lg = np.log(rt["mid"])
        sim_lg = np.log(sims[feed][0]["_ticks_long"])
        for a, b in ((3, 1), (1, 3), (2, 10)):
            pred = (b + bp) / (a + b + 2 * bp)
            closed = (b + G.BETA) / (a + b + 2 * G.BETA)
            ps, ns = tick_barrier(sim_lg, a, b, u)
            pr, nr = tick_barrier(real_lg, a, b, u)
            zs = (ps - pred) / math.sqrt(0.25 / ns) if ns else float("nan")
            zr = (pr - pred) / math.sqrt(0.25 / nr) if nr else float("nan")
            print(f"{feed:26s} {tpb:4d} {a}:{b:<3d} {ps:11.4f} {ns:7d} {pr:12.4f} "
                  f"{nr:7d} {pred:10.4f} {closed:10.4f} {b / (a + b):11.4f} "
                  f"{zs:+7.2f} {zr:+7.2f}")
            tickrows.append({"feed": feed, "tpb": tpb, "a": a, "b": b, "pred": pred,
                             "p_sim": ps, "n_sim": ns, "p_real": pr, "n_real": nr,
                             "z_sim": zs, "z_real": zr, "closed": closed})
            ledger.append({"test": "tick-monitored P(up) within 0.005 of the prediction",
                           "feed": f"{feed} {a}:{b}", "value": ps - pred,
                           "fired": abs(ps - pred) > 0.005})
    print("\n     pooled over feeds, by tick rate and geometry:")
    print(f"     {'tpb':>4s} {'a:b':>5s} {'sim':>9s} {'real':>9s} {'+-SE real':>10s} "
          f"{'predicted':>10s} {'z real':>7s} {'close-mon':>10s} {'z vs close-mon':>15s}")
    for tpb in (30, 60):
        for a, b in ((3, 1), (1, 3), (2, 10)):
            rows = [r for r in tickrows if r["tpb"] == tpb and r["a"] == a and r["b"] == b]
            if not rows:
                continue
            nr = sum(r["n_real"] for r in rows)
            ns = sum(r["n_sim"] for r in rows)
            pr = sum(r["p_real"] * r["n_real"] for r in rows) / max(nr, 1)
            ps = sum(r["p_sim"] * r["n_sim"] for r in rows) / max(ns, 1)
            se = math.sqrt(0.25 / max(nr, 1))
            pred, closed = rows[0]["pred"], rows[0]["closed"]
            print(f"     {tpb:4d} {a}:{b:<3d} {ps:9.4f} {pr:9.4f} {se:10.4f} "
                  f"{pred:10.4f} {(pr - pred) / se:+7.2f} {closed:10.4f} "
                  f"{(pr - closed) / se:+15.2f}")
    payload["tick_barrier"] = tickrows

    # --------------------------------------------------- cross-feed structure --
    print("\n[10] THE CROSS-FEED STRUCTURE - twins must be uncorrelated and no family")
    print("     may share a factor. Twelve rebuilds on twelve independent seeds, the same")
    print("     86,410 bars the real feeds carry, all 66 pairs.")
    feeds = list(sims)
    n_bars = min(real[f2]["n_bars"] for f2 in feeds)
    mat_s, mat_r = [], []
    for i, f2 in enumerate(feeds):
        bb = simulate_vol(f2, NOMINAL[f2], real[f2]["p0"], real[f2]["grid"], n_bars,
                          1000 + 17 * i)
        mat_s.append(G.logrets(bb["close"], bb["ts"])[:n_bars - 1])
        mat_r.append(G.logrets(real[f2]["_close"], real[f2]["_ts"])[:n_bars - 1])
    ln = min(*(x.size for x in mat_s), *(x.size for x in mat_r))
    sm = np.array([x[:ln] for x in mat_s])
    rm = np.array([x[:ln] for x in mat_r])
    cs = np.corrcoef(sm)
    cr = np.corrcoef(rm)
    iu = np.triu_indices(len(feeds), 1)
    band = 2.0 / math.sqrt(ln)
    print(f"     n = {ln} bars, 2-SE band +-{band:.5f}")
    print(f"     {'':22s} {'largest |r|':>12s} {'mean |r|':>10s} {'#past 2SE':>10s} "
          f"{'lead eigval':>12s}")
    for nm, c in (("real", cr), ("rebuilt", cs)):
        v = c[iu]
        ev = float(np.linalg.eigvalsh(c).max())
        print(f"     {nm:22s} {np.abs(v).max():12.5f} {np.abs(v).mean():10.5f} "
              f"{int((np.abs(v) > band).sum()):10d} {ev:12.5f}")
    kc = G.ks2(cr[iu], cs[iu])
    print(f"     KS between the two sets of 66 correlations: D={kc['D']:.4f} p={kc['p']:.4f}")
    twins = [(a, a.replace("_index", "_1s_index")) for a in feeds
             if "_1s_" not in a and a.replace("_index", "_1s_index") in feeds]
    print(f"     the twin pairs specifically ({len(twins)} of them):")
    for a, b in twins:
        ia, ib = feeds.index(a), feeds.index(b)
        print(f"       {a:26s} / {b:26s} real {cr[ia, ib]:+.5f}  rebuilt {cs[ia, ib]:+.5f}")
    big_s = float(np.abs(cs[iu]).max())
    big_r = float(np.abs(cr[iu]).max())
    ledger.append({"test": "rebuilt max |cross-corr| no larger than the real one + 2SE",
                   "feed": "all 66 pairs", "value": big_s,
                   "fired": big_s > big_r + band})
    ledger.append({"test": "KS between real and rebuilt correlation sets does not reject",
                   "feed": "all 66 pairs", "value": kc["p"], "fired": kc["reject"]})
    payload["crossfeed"] = {"n": int(ln), "band": band, "max_real": big_r, "max_sim": big_s,
                            "eig_real": float(np.linalg.eigvalsh(cr).max()),
                            "eig_sim": float(np.linalg.eigvalsh(cs).max()),
                            "ks": kc,
                            "twins": [{"a": a, "b": b,
                                       "real": float(cr[feeds.index(a), feeds.index(b)]),
                                       "sim": float(cs[feeds.index(a), feeds.index(b)])}
                                      for a, b in twins]}

    # ------------------------------------------------------------ jump family --
    print("\n[11] THE JUMP FAMILY - two readings of the 1.322, and the data chooses")
    print("     A: the name is the diffusion, jumps add 1.322^2-1 = 0.7477 of its variance")
    print("     B: the diffusion itself runs at 1.322x the name, jumps on top")
    jrows = []
    for feed, nom in JUMP_NOMINAL.items():
        rb = G.real_bars(feed)
        rt = G.real_ticks(feed)
        if not rb.get("n") or not rt.get("n"):
            continue
        grid = G.quote_grid(rt["mid"])
        rr = G.logrets(rb["close"], rb["ts"])
        # the jump rate, measured: a tick move past 10x the median absolute move
        d = np.diff(rt["mid"])
        med = float(np.median(np.abs(d[d != 0])))
        idx = np.flatnonzero(np.abs(d) > 10 * med)
        span_min = (rt["ts"][-1] - rt["ts"][0]) / 60000.0
        rate = idx.size / span_min if span_min else float("nan")
        sigma_min = (nom / 100.0) / math.sqrt(G.MINUTES_PER_YEAR)
        # spec A: E[J^2] = 0.7477 * sigma_min^2 * minutes-per-jump
        jsize_a = math.sqrt(0.7477 * sigma_min ** 2 / rate) if rate > 0 else 0.0
        n_bars = min(rb["n"] * JMULT, 700_000)
        tick_s = 1.0
        row = {"feed": feed, "nominal": nom, "rate_per_min": rate,
               "min_per_jump": 1.0 / rate if rate else float("nan"),
               "real_ann": G.ann_vol(rr), "real_kurt": G.kurtosis(rr),
               "jsize_a": jsize_a}
        pool = np.abs(d[idx]) / rt["mid"][idx]          # measured jump, in log units
        row["jsize_measured"] = float(np.sqrt((pool ** 2).mean())) if pool.size else 0.0
        for tag, sig, js in (("A", nom, jsize_a), ("B", nom * JUMP_MULT, jsize_a),
                             ("A+", nom, row["jsize_measured"])):
            rngj = np.random.default_rng(SEEDS[0] + len(tag))
            st = G.bars_from_stream(
                G.gen_jump(n_bars * 60, sig, tick_s, rate, js, float(rb["close"][0]),
                           grid, rngj), 60, n_bars)
            r2 = G.logrets(st["close"], st["ts"])
            k = G.ks2(rr, r2, rng=rng)
            row[tag] = {"ann": G.ann_vol(r2), "kurt": G.kurtosis(r2), "ks": k,
                        "ratio": G.ann_vol(r2) / nom}
        jrows.append(row)
    print("     A+: spec A with the jump magnitude resampled from the feed's own jumps")
    print(f"{'feed':20s} {'name':>5s} {'min/jump':>9s} {'jsz A':>9s} {'jsz meas':>9s} "
          f"{'real ann':>9s} {'A ann':>8s} {'A/name':>7s} {'B/name':>7s} {'A+/name':>8s} | "
          f"{'real kurt':>10s} {'A kurt':>8s} {'A+ kurt':>8s} | {'A KS p':>8s} {'B KS p':>8s} "
          f"{'A+ KS p':>8s}")
    for r2 in jrows:
        print(f"{r2['feed']:20s} {r2['nominal']:5.0f} {r2['min_per_jump']:9.2f} "
              f"{r2['jsize_a']:9.2e} {r2['jsize_measured']:9.2e} "
              f"{r2['real_ann']:9.3f} {r2['A']['ann']:8.3f} {r2['A']['ratio']:7.4f} "
              f"{r2['B']['ratio']:7.4f} {r2['A+']['ratio']:8.4f} | {r2['real_kurt']:10.3f} "
              f"{r2['A']['kurt']:8.3f} {r2['A+']['kurt']:8.3f} | {r2['A']['ks']['p']:8.4f} "
              f"{r2['B']['ks']['p']:8.4f} {r2['A+']['ks']['p']:8.4f}")
        ledger.append({"test": "jump spec A reproduces the 1.322 multiplier", "feed": r2["feed"],
                       "value": r2["A"]["ratio"],
                       "fired": abs(r2["A"]["ratio"] - JUMP_MULT) > 0.05})
    payload["jump"] = json.loads(json.dumps(jrows, default=float))

    # ----------------------------------------------------------------- ledger --
    print("\n[12] THE FAILURE LEDGER - every pre-registered condition and whether it fired")
    by: dict[str, list] = {}
    for e in ledger:
        by.setdefault(e["test"], []).append(e)
    print(f"{'condition':58s} {'cells':>6s} {'fired':>6s} {'worst cell':>34s}")
    nfired = 0
    for name, es in by.items():
        f2 = [e for e in es if e["fired"]]
        nfired += len(f2)
        worst = max(es, key=lambda e: abs(e.get("value") or 0)) if es else None
        w = f"{worst['feed']} {worst['value']:.5g}" if worst else ""
        print(f"{name:58s} {len(es):6d} {len(f2):6d} {w:>34s}")
    print(f"\n    {len(ledger)} pre-registered comparisons, {nfired} fired.")
    payload["ledger"] = ledger

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        json.dump(json.loads(json.dumps(payload, default=float)), fh, indent=1)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
