"""Rebuild Step Index and Range Break, and find out what the specification is
missing.

These two are the lattice families: both move one fixed unit a tick, both print
once a second, and both are described in `deriving.md` - but described to very
different depths, which is the point of putting them on one page.

**Step Index is fully specified.** A fixed 0.1 increment, a fair coin, a spread
of exactly one step, one tick a second. Four numbers, and the rebuild gets
nothing else. Section three of `deriving.md` then says the whole instrument is
gambler's ruin: `P(target) = S/(S+T)`, `E[tau] = S*T` steps, and `(S+d)/(S+T+2d)`
when the fill triggers one step past the level.

**Range Break is not.** `deriving.md` publishes the break rate - memoryless at
86.5 and 178.8 minutes - and measures the consequence: dropping the bars that
contain a break leaves a process that is **sub-diffusive by 3.6x and 8.9x**,
while the all-bars variance ratio stays flat over three orders of magnitude in
horizon. It says in as many words that the range rule itself is unknown: "how
wide, how it resets, what counts as a bounce". So a rebuild needs two parameters
that are not in the specification, and the honest experiment is to estimate them
from something *other* than the variance-ratio curve and then predict that curve.

The mechanism proposed here is the simplest one that could produce both facts at
once: a `+-1` walk that **bounces** off both edges of a range of fixed width, and
a memoryless break that jumps the price and opens a new range where it lands.
Two candidate re-range rules are built and both are reported, because
`deriving.md` publishes neither and they are different generators:

* `edge` - the break point becomes the new range's near edge, so the price has
  the whole range in front of it;
* `edge_far` - the break overshoots and the new range opens behind it, so the
  price starts at the far edge and the next move is back into the range;
* `centre` - the new range is centred on the break point.

The band width is estimated from the *visited* range between breaks and the jump
by measuring break bars directly; the six variance ratios at
n = 1, 5, 20, 100, 500, 1000 are then out-of-sample.

## What would count as failure, written before any number was looked at

1. **Step fails** if the rebuilt tick-magnitude concentration is below 99.99% on
   a single value, where the feed reads **99.9988%**.
2. **Step fails** if `p(up)` recovered from the rebuild is more than 3 SE from
   the 0.5 that went in, or if more than 2 of the 30 sign autocorrelations
   exceed `+-3/sqrt(n)` (1.5 expected), or if `|runs z| > 3`.
3. **Step fails** if the rebuilt gambler's-ruin hit rates and durations miss
   `S/(S+T)` and `S*T` by more than the real feed misses them - which
   `deriving.md` puts at 0.03-0.07 standard errors on `P` and -2.2% to +6.9% on
   `E[tau]`.
4. **Step fails** if a chi-square on the one-minute change distribution - a sum
   of sixty coin flips, 61 atoms, not a continuum - rejects real against
   rebuilt at alpha = 0.05.
5. **Range Break fails** if the rebuilt all-bars variance ratio is not flat.
   Flat is defined here, in advance, as `max/min <= 1.35` over
   n in {1,5,20,100,500,1000}: the real RB100 gives 4.713/4.217 = **1.118** and
   RB200 5.917/5.176 = **1.143**, and the n=1000 cell carries a 15% standard
   error of its own, so anything past 1.35 is a real shape difference.
6. **Range Break fails** if the feed's own ex-break variance ratio sits more
   than **3 standard deviations** from the middle of a `NULL_SEEDS`-seed rebuild
   ensemble simulated at the feed's own sample size, at any
   n in {1, 5, 20, 100, 500, 1000}. The curve to reproduce runs from ~1.0 at
   n=1 to the feed's **0.283** (RB100) and **0.112** (RB200) at n >= 100.
7. **Range Break fails** if the break waiting-time CV is outside 0.85-1.15
   (real: 1.003 and 1.075) or the RB100/RB200 break-rate ratio is outside
   2.066 +- 0.30 (the real 95% CI is [1.86, 2.30]).
8. **The run is void** if flatness is achieved degenerately - a price that does
   not move between breaks, or a break in more than one bar in ten. Both are
   checked and printed.
9. **The run is void** if a statistic lands on exactly its null, or if the
   positive control fails: a rebuild with `p_up = 0.501` instead of 0.5, and one
   with the range switched off entirely, must both be caught by this battery.


## Amended before the real data was touched, and why

Every harness here was first run end to end against a **synthetic** database -
sixty days of bars and twenty-four hours of ticks for all twenty-six feeds,
generated by these same generators - so that a crash or a broken test would
surface on data whose truth was known rather than on the lab. Three conditions
were rewritten during that dry run. Each amendment is recorded here rather than
quietly applied, because a failure condition edited after seeing the answer is
not a failure condition, and the only defence is to say exactly when it was
edited and what forced it.

* **The Range Break tolerance in condition 6** was written as "within 2 standard
  errors", with the standard error taken as `sqrt(2/k)` on `k` non-overlapping
  windows. On the dry run that test rejected the *true* parameters at up to
  **4.6 standard errors** on data this very generator had produced. The Gaussian
  standard error is simply wrong for a variance ratio on a jump process, so it
  was replaced by a Monte Carlo null: the feed is scored against an ensemble of
  rebuilds at the feed's own sample size, at 3 ensemble standard deviations.
  The tolerance got *looser* and that is the honest direction to note, but the
  estimator got right, which is the reason.
* **The `edge` rule was added during the dry run**, against `deriving.md`'s
  *published* ex-break curve rather than against any measurement of my own. A
  centred range needs a band of 132 steps to carry the plateau at n >= 100, and
  a band that wide relaxes in 3,500 ticks against a 5,190-tick break interval,
  so it cannot also be confined at n = 20. Anchoring the new range on the break
  point quadruples the displacement accumulated inside a range at the same
  width, which lets the band be half as wide and relax three times faster. Both
  rules are built and both are reported; nothing was dropped.
* **The band width is fitted on the visited range**, and the dry run showed the
  median alone cannot do it: that distribution has an atom at the band width, so
  a one-step error moves half the mass and leaves the median where it was. The
  fit now bisects on the median and then minimises the KS distance to the
  measured visited-range distribution over a seven-step bracket. It still never
  sees a variance ratio.

## The controls

* **the feed against itself**, first half against last half, through the same
  tests.
* **a free walk with no range at all**, which must produce an ex-break curve
  flat at 1.0 - if it does not, the sub-diffusion estimator is broken and the
  Range Break result cannot be read.
* **`p_up = 0.501`**, a bias of 23 standard errors on the 60-day bar sample,
  which the fair-coin test must see.
"""

from __future__ import annotations

import json
import math
import os
import sys
from collections import Counter

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rebuildgen as G

OUT = os.environ.get("OUT", os.path.expanduser("~/till_infinity/logs/rebuildstep.json"))
SEEDS = [int(s) for s in os.environ.get("SEEDS", "20260912,20260913,20260914,20260915").split(",")]
MULT = int(os.environ.get("MULT", "10"))
RBMULT = int(os.environ.get("RBMULT", "5"))
TPB = 60                      # one tick a second
STEP_SIZE = 0.1               # the published increment
VR_N = (1, 5, 20, 100, 500, 1000)
#: A one-minute bar of a one-unit-a-tick series cannot span more than sixty
#: units by stepping, so a range past this contains a break. `genrange.py`'s cut.
BREAK_CUT = 1.1 * TPB
#: The two candidate re-range rules. `deriving.md` publishes neither.
ANCHORS = ("edge", "edge_far", "centre")
MAIN_ANCHOR = "edge"
#: Rebuilds at the feed's own sample size, used as the null distribution for
#: every variance-ratio cell rather than a Gaussian standard error.
NULL_SEEDS = int(os.environ.get("NULL_SEEDS", "12"))


# ------------------------------------------------------------ measurements --
def magnitude_concentration(mid: np.ndarray) -> dict:
    d = np.round(np.diff(mid), 10)
    nz = np.abs(d[d != 0])
    if not nz.size:
        return {}
    c = Counter(np.round(nz, 8))
    top = c.most_common(6)
    return {"n_moves": int(nz.size), "zero_moves": int((d == 0).sum()),
            "mode": float(top[0][0]), "share": top[0][1] / nz.size,
            "top": [(float(k), int(v), v / nz.size) for k, v in top]}


def coin(mid: np.ndarray) -> dict:
    d = np.diff(mid)
    s = np.sign(d)
    s = s[s != 0]
    n = s.size
    p = float((s > 0).mean())
    se = math.sqrt(0.25 / n)
    band = 3.0 / math.sqrt(n)
    acfs = {lag: G.acf(s, lag) for lag in range(1, 31)}
    return {"n": n, "p_up": p, "se": se, "z": (p - 0.5) / se, "band": band,
            "acf": acfs, "n_outside": sum(1 for v in acfs.values() if abs(v) > band),
            "runs_z": G.runs_z(s)}


def ruin(mid: np.ndarray, step: float, past: bool = False) -> list[dict]:
    """Non-overlapping symmetric-ish barrier replay on the lattice.

    `past=False` triggers when price reaches the level, `past=True` when it is
    strictly beyond it - `deriving.md` section three shows the two conventions
    give `S/(S+T)` and `(S+d)/(S+T+2d)` and that the second is what
    `generators.md`'s replay measured.
    """
    out = []
    lat = np.round(mid / step).astype(np.int64)
    for stop, tgt in ((5, 5), (5, 10), (5, 15), (10, 10), (5, 25)):
        i, hits, taus = 0, 0, []
        n = lat.size
        while i < n - 1:
            x0 = lat[i]
            j = i + 1
            res = 0
            while j < n:
                d = lat[j] - x0
                if (d > tgt) if past else (d >= tgt):
                    res = 1
                    break
                if (d < -stop) if past else (d <= -stop):
                    res = -1
                    break
                j += 1
            if res == 0:
                break
            hits += 1 if res > 0 else 0
            taus.append(j - i)
            i = j
        if len(taus) < 30:
            continue
        t = np.array(taus, dtype=float)
        d0 = 1.0
        out.append({"S": stop, "T": tgt, "n": len(taus), "p": hits / len(taus),
                    "p_theory": ((stop + d0) / (stop + tgt + 2 * d0) if past
                                 else stop / (stop + tgt)),
                    "se_p": math.sqrt(0.25 / len(taus)),
                    "etau": float(t.mean()), "etau_theory": float(stop * tgt),
                    "se_tau": float(t.std(ddof=1) / math.sqrt(t.size))})
    return out


def break_bars(bars: dict, step: float = 1.0) -> np.ndarray:
    """Bars whose range is larger than sixty unit steps can span.

    The cut is in *price*, so it has to carry the step size. `genrange.py` wrote
    it as a bare 66 because Range Break happens to step by exactly 1.0 in price;
    keeping the step explicit means the same function reads a rebuild quoted on
    any grid.
    """
    return (bars["high"] - bars["low"]) > BREAK_CUT * step


def vr_absolute(chg: np.ndarray, n: int, step: float, tpb: int = TPB) -> float:
    """`deriving.md` section four: `Var(C_{t+n} - C_t) / (n * tpb * d^2)`.

    1.0 is a free lattice walk of `tpb` unit steps a bar. Non-overlapping sums,
    so the standard error is `sqrt(2/k)` on `k = len(chg)//n` windows.
    """
    if chg.size < n * 20:
        return float("nan")
    agg = chg[: (chg.size // n) * n].reshape(-1, n).sum(axis=1)
    if agg.size < 10:
        return float("nan")
    return float(agg.var(ddof=0) / (n * tpb * step * step))


def vr_curves(bars: dict, step: float) -> dict:
    """Three readings, because the published table has to be reproduced before
    it can be used as a target.

    `all` is every bar. `splice` drops the break bars' own changes and sums what
    is left as if contiguous. `window` keeps only n-bar windows with no break in
    them. They are different estimators and only one of them can produce the
    published 0.279 at n=1000, since a thousand-minute window with no break has
    probability 1e-5.
    """
    cl = bars["close"]
    chg = np.diff(cl)
    brk = break_bars(bars, step)[1:]
    out = {"n_bars": int(cl.size), "n_breaks": int(brk.sum()),
           "bars_per_break": cl.size / max(int(brk.sum()), 1),
           "all": {}, "splice": {}, "window": {}, "se": {}}
    keep = chg[~brk]
    for n in VR_N:
        out["all"][n] = vr_absolute(chg, n, step)
        out["splice"][n] = vr_absolute(keep, n, step)
        out["se"][n] = math.sqrt(2.0 / max(chg.size // n, 1))
        # windows with no break: cumulative sums, sliding, break-free only
        if chg.size > n * 20:
            cs = np.concatenate([[0.0], np.cumsum(chg)])
            bc = np.concatenate([[0], np.cumsum(brk.astype(np.int64))])
            i = np.arange(0, chg.size - n)
            good = (bc[i + n] - bc[i]) == 0
            if good.sum() > 30:
                d = cs[i + n][good] - cs[i][good]
                out["window"][n] = float(d.var(ddof=0) / (n * TPB * step * step))
                out["window"][f"{n}_n"] = int(good.sum())
            else:
                out["window"][n] = float("nan")
                out["window"][f"{n}_n"] = int(good.sum())
    # the break's share of variance, deriving.md's other statement
    out["break_share"] = {}
    for n in (1, 200):
        a, s = out["all"].get(n), out["splice"].get(n)
        if a and s and not math.isnan(a) and not math.isnan(s):
            out["break_share"][n] = 1.0 - s / a
    return out


def break_stats(bars: dict, step: float) -> dict:
    brk = break_bars(bars, step)
    idx = np.flatnonzero(brk)
    gaps = np.diff(idx).astype(float)
    jump = np.abs(bars["close"][idx] - bars["open"][idx]) / step
    span = bars["n"]
    return {"n_breaks": int(idx.size), "minutes_per_break": span / max(idx.size, 1),
            "gap_cv": float(gaps.std(ddof=1) / gaps.mean()) if gaps.size > 2 else float("nan"),
            "gap_mean": float(gaps.mean()) if gaps.size else float("nan"),
            "jump_median": float(np.median(jump)) if jump.size else float("nan"),
            "jump_mean": float(jump.mean()) if jump.size else float("nan"),
            "jump_sd": float(jump.std(ddof=1)) if jump.size > 2 else float("nan"),
            "jump_q": {q: float(np.percentile(jump, q)) for q in (10, 50, 90, 99)}
            if jump.size else {},
            "_jump": jump, "_idx": idx}


def visited_ranges(bars: dict, step: float) -> np.ndarray:
    """max(high) - min(low) over each run of bars between two breaks, in steps.

    This is the statistic the band width is fitted on. It is not the variance
    ratio, and it is not the break rate, so the six variance ratios stay
    out-of-sample.
    """
    brk = break_bars(bars, step)
    idx = np.flatnonzero(brk)
    out = []
    for a, b in zip(idx, idx[1:], strict=False):
        if b - a < 5:
            continue
        out.append((bars["high"][a + 1:b].max() - bars["low"][a + 1:b].min()) / step)
    return np.array(out)


# ------------------------------------------------------------- simulation ----
def sim_step(n_bars: int, p_up: float, seed: int, p0: float) -> dict:
    rng = np.random.default_rng(seed)
    return G.bars_from_stream(G.gen_step(n_bars * TPB, STEP_SIZE, p_up, p0, rng),
                              TPB, n_bars, keep_ticks=min(n_bars * TPB, 200_000))


def sim_rb(n_bars: int, band: int, mean_break_ticks: float, jump_pool, seed: int,
           p0: float, step: float, anchor: str = "edge") -> dict:
    rng = np.random.default_rng(seed)
    return G.bars_from_stream(
        G.gen_rangebreak(n_bars * TPB, step, band, mean_break_ticks, 0.0, p0, rng,
                         jump_pool=jump_pool, anchor=anchor),
        TPB, n_bars, keep_ticks=min(n_bars * TPB, 200_000))


def fit_band(target: np.ndarray, mean_break_ticks: float, jump_pool, p0: float,
             step: float, seed: int, n_bars: int = 60_000,
             anchor: str = "edge") -> tuple[int, float, float]:
    """One parameter, fitted on the *visited* range and nothing else.

    Bisection to match the median, then a short scan around it minimising the
    two-sample KS distance between the simulated and the measured visited-range
    distributions. The median alone is not enough because that distribution has
    an atom at the band width - a walk that crosses its range before the break
    visits exactly the band - so a one-step error moves half the mass and the
    median cannot see it.

    Nothing about the variance-ratio curve enters here, which is what keeps that
    curve a prediction.
    """
    target_median = float(np.median(target))
    lo, hi = 8, 4000
    for _ in range(12):
        mid = (lo + hi) // 2
        v = visited_ranges(sim_rb(n_bars, mid, mean_break_ticks, jump_pool, seed, p0,
                                  step, anchor), step)
        got = float(np.median(v)) if v.size > 20 else float("nan")
        if math.isnan(got):
            break
        if got < target_median:
            lo = mid
        else:
            hi = mid
        if hi - lo <= 1:
            break
    base = (lo + hi) // 2
    best, best_d, best_med = base, float("inf"), float("nan")
    for band in range(max(8, base - 4), base + 5):
        v = visited_ranges(sim_rb(n_bars, band, mean_break_ticks, jump_pool, seed, p0,
                                  step, anchor), step)
        if v.size < 20:
            continue
        d = G.ks2(target, v)["D"]
        if d < best_d:
            best, best_d, best_med = band, d, float(np.median(v))
    return best, best_med, best_d


#: `deriving.md` section four's table, as published. These are measurements of
#: the real feed and the three candidate re-range rules are scored against them
#: directly, which needs no database - so this comparison runs anywhere and is
#: the one part of the Range Break study that does not wait on the lab.
PUBLISHED_VR = {
    "range_break_100_index": {
        "minutes_per_break": 86.6,
        "all": {1: 4.217, 5: 4.225, 20: 4.271, 100: 4.295, 500: 4.441, 1000: 4.713},
        "splice": {1: 0.978, 5: 0.730, 20: 0.436, 100: 0.283, 500: 0.274, 1000: 0.279},
    },
    "range_break_200_index": {
        "minutes_per_break": 178.9,
        "all": {1: 5.645, 5: 5.669, 20: 5.681, 100: 5.917, 500: 5.685, 1000: 5.176},
        "splice": {1: 0.930, 5: 0.750, 20: 0.477, 100: 0.192, 500: 0.116, 1000: 0.112},
    },
}


def score_against_published(feed: str, anchor: str, band: int, jump: float,
                            n_bars: int, seed: int) -> dict:
    """Simulate one candidate and score its variance-ratio curve against the
    published one, in absolute deviation on the ex-break series plus the
    flatness of the all-bars series."""
    tgt = PUBLISHED_VR[feed]
    mbt = tgt["minutes_per_break"] * TPB
    bb = sim_rb(n_bars, band, mbt, np.array([float(jump)]), seed, 5000.0, 1.0, anchor)
    cur = vr_curves(bb, 1.0)
    allv = [cur["all"][n] for n in VR_N]
    err = [cur["splice"][n] - tgt["splice"][n] for n in VR_N]
    return {"anchor": anchor, "band": band, "jump": jump,
            "all": allv, "splice": [cur["splice"][n] for n in VR_N],
            "err": err, "mae": float(np.mean(np.abs(err))),
            "flat": max(allv) / min(allv),
            "flat_target": max(tgt["all"].values()) / min(tgt["all"].values()),
            "all_level_err": float(np.mean(allv) - np.mean(list(tgt["all"].values())))}


def published_study(n_bars: int, seed: int) -> dict:
    """Scan the two unpublished parameters for each candidate rule, against the
    published curve. No database, no fitting to anything measured here."""
    out: dict[str, list] = {}
    print("\n[0] THE RANGE RULE, SCORED AGAINST `deriving.md`'s PUBLISHED CURVE")
    print("    Three candidate re-range rules and a scan of the two parameters the")
    print("    specification does not contain. Nothing here reads research.db: the")
    print("    published variance-ratio table is the measurement being matched.")
    for feed in PUBLISHED_VR:
        tgt = PUBLISHED_VR[feed]
        best: list = []
        for anchor in ANCHORS:
            grid = ((45, 60, 66, 75, 90, 110) if anchor != "centre"
                    else (110, 132, 160, 190))
            for band in grid:
                for jump in (120.0, 140.0, 160.0, 190.0, 230.0):
                    r = score_against_published(feed, anchor, band, jump, n_bars, seed)
                    # the all-bars level has to be right too, not just the shape
                    r["score"] = r["mae"] + abs(r["all_level_err"]) / 10.0
                    best.append(r)
        best.sort(key=lambda r: r["score"])
        out[feed] = best
        pub_flat = max(tgt["all"].values()) / min(tgt["all"].values())
        print(f"\n    {feed}: published all-bars flatness {pub_flat:.3f}, "
              f"break every {tgt['minutes_per_break']:.1f} minutes")
        print(f"      {'rule':9s} {'band':>5s} {'|J|':>5s} {'MAE':>7s} {'flat':>6s} "
              + " ".join(f"{'n=' + str(n):>8s}" for n in VR_N))
        print(f"      {'PUBLISHED':9s} {'':>5s} {'':>5s} {'':>7s} {pub_flat:6.3f} "
              + " ".join(f"{tgt['splice'][n]:8.3f}" for n in VR_N))
        for anchor in ANCHORS:
            r = next(x for x in best if x["anchor"] == anchor)
            print(f"      {anchor:9s} {r['band']:5d} {r['jump']:5.0f} {r['mae']:7.4f} "
                  f"{r['flat']:6.3f} " + " ".join(f"{v:8.3f}" for v in r["splice"]))
            print(f"      {'':9s} {'':5s} {'':5s} {'':7s} {'':6s} "
                  + " ".join(f"{v:+8.3f}" for v in r["err"]) + "   <- residual")
    return out


def main() -> None:
    rng = np.random.default_rng(4242)
    ledger: list[dict] = []
    payload: dict = {"seeds": SEEDS}
    print("=" * 120)
    print("REBUILDING STEP INDEX AND RANGE BREAK")
    print(f"  seeds {SEEDS}   {G.machine()}")
    print("=" * 120)

    # ---------------------------------------------------------- step index ----
    payload["published"] = json.loads(json.dumps(
        {f: v[:6] for f, v in published_study(
            int(os.environ.get("PUB_BARS", "120000")), SEEDS[0]).items()}, default=float))

    print("\n[1] STEP INDEX - the feed, and the four numbers the rebuild is given")
    rb = G.real_bars("step_index")
    rt = G.real_ticks("step_index")
    mc = magnitude_concentration(rt["mid"])
    cn = coin(rt["mid"])
    step = mc["mode"]
    spread_med = float(np.median(rt["spread"]))
    print(f"    ticks {rt['n']}  {rt['per_sec']:.4f}/s  bars {rb['n']}")
    print(f"    step magnitude mode {step:g} carries {mc['share']:.6%} of "
          f"{mc['n_moves']} moves; zero moves {mc['zero_moves']}")
    print("    top magnitudes: " + ", ".join(f"{k:g}x{v}" for k, v, _ in mc["top"][:4]))
    print(f"    p(up) ticks {cn['p_up']:.6f} +- {cn['se']:.6f}  z {cn['z']:+.2f}  "
          f"runs z {cn['runs_z']:+.3f}  acf lags outside band {cn['n_outside']}/30")
    print(f"    spread median {spread_med:g} = {spread_med / step:.3f} steps")
    chg_r = np.diff(rb["close"])
    print(f"    60-day bar sample: {chg_r.size} minutes, mean change {chg_r.mean():+.5e}, "
          f"implied p(up) {0.5 + chg_r.mean() / (2 * step * TPB):.6f}")

    print("\n[2] STEP INDEX REBUILT - fixed 0.1, fair coin, 60 ticks a minute")
    print(f"{'seed':>10s} {'bars':>9s} {'concentration':>14s} {'p_up':>10s} {'z':>7s} "
          f"{'runs z':>8s} {'acf>band':>9s} {'ann vol':>9s}")
    sruns = []
    for sd in SEEDS:
        bb = sim_step(min(rb["n"] * MULT, 900_000), 0.5, sd, float(rb["close"][0]))
        m2 = magnitude_concentration(bb["ticks"])
        c2 = coin(bb["ticks"])
        r2 = G.logrets(bb["close"], bb["ts"])
        sruns.append({"bars": bb, "mc": m2, "coin": c2, "ann": G.ann_vol(r2)})
        print(f"{sd:>10d} {bb['n']:9d} {m2['share']:14.6%} {c2['p_up']:10.6f} "
              f"{c2['z']:+7.2f} {c2['runs_z']:+8.3f} {c2['n_outside']:9d} "
              f"{G.ann_vol(r2):9.3f}", flush=True)
    conc = G.spread_across([r["mc"]["share"] for r in sruns])
    ledger.append({"test": "Step concentration >= 99.99% on one magnitude", "feed": "step_index",
                   "value": conc["mean"], "fired": conc["mean"] < 0.9999})
    zs = G.spread_across([r["coin"]["z"] for r in sruns])
    ledger.append({"test": "Step recovered p(up) within 3 SE of the 0.5 put in",
                   "feed": "step_index", "value": zs["mean"], "fired": abs(zs["mean"]) > 3})
    ob = G.spread_across([float(r["coin"]["n_outside"]) for r in sruns])
    ledger.append({"test": "Step sign acf: at most 2 of 30 lags outside the band",
                   "feed": "step_index", "value": ob["mean"], "fired": ob["mean"] > 2})
    rz = G.spread_across([r["coin"]["runs_z"] for r in sruns])
    ledger.append({"test": "Step |runs z| <= 3", "feed": "step_index", "value": rz["mean"],
                   "fired": abs(rz["mean"]) > 3})
    print(f"    real concentration {mc['share']:.6%}  rebuilt {conc['mean']:.6%} "
          f"(sd {conc['sd']:.2e} over {len(SEEDS)} seeds)")

    print("\n[3] STEP INDEX - gambler's ruin off the rebuilt path against the closed form")
    print(f"{'S:T':>7s} {'':>4s} {'n':>7s} {'P(hit)':>9s} {'derived':>9s} {'z':>7s} "
          f"{'E[tau]':>9s} {'S*T':>7s} {'err':>8s}")
    ru_real = ruin(rt["mid"], step)
    ru_sim = ruin(sruns[0]["bars"]["ticks"], STEP_SIZE)
    for tag, rows in (("real", ru_real), ("sim", ru_sim)):
        for r2 in rows:
            z = (r2["p"] - r2["p_theory"]) / r2["se_p"]
            print(f"{r2['S']}:{r2['T']:<5d} {tag:>4s} {r2['n']:7d} {r2['p']:9.4f} "
                  f"{r2['p_theory']:9.4f} {z:+7.2f} {r2['etau']:9.2f} {r2['etau_theory']:7.0f} "
                  f"{100 * (r2['etau'] / r2['etau_theory'] - 1):7.2f}%")
            if tag == "sim":
                ledger.append({"test": "Step rebuilt hit rate within 3 SE of S/(S+T)",
                               "feed": f"{r2['S']}:{r2['T']}", "value": z,
                               "fired": abs(z) > 3})
    ru_past = ruin(sruns[0]["bars"]["ticks"], STEP_SIZE, past=True)
    print("    the fill-one-step-past convention, which `deriving.md` shows is what")
    print("    `generators.md` actually measured:")
    for r2 in ru_past:
        print(f"      {r2['S']}:{r2['T']:<4d} rebuilt {r2['p']:.4f}  "
              f"derived (S+d)/(S+T+2d) {r2['p_theory']:.4f}")

    print("\n[4] STEP INDEX - the one-minute change distribution, sixty coin flips")
    chg_s = np.diff(sruns[0]["bars"]["close"])
    c2t = G.chi2_hist(chg_r, chg_s, nbin=40)
    kk = G.ks2(chg_r, chg_s, rng=rng)
    h = chg_r.size // 2
    kc = G.ks2(chg_r[:h], chg_r[h:], rng=rng)
    print(f"    real n={chg_r.size}  rebuilt n={chg_s.size}")
    print(f"    chi-square p {c2t['p']:.4f} (df {c2t['df']})   KS D {kk['D']:.5f} "
          f"crit {kk['D_crit_05']:.5f} p {kk['p']:.4f}   n* {G.nstar(kk['D']):.3g}")
    print(f"    control, real first half against real last half: D {kc['D']:.5f} "
          f"p {kc['p']:.4f}")
    ledger.append({"test": "Step 1m change distribution: chi-square does not reject",
                   "feed": "step_index", "value": c2t["p"], "fired": bool(c2t["reject"])})

    print("\n[5] STEP INDEX - the positive control, p_up = 0.501")
    bb = sim_step(rb["n"], 0.501, SEEDS[0] + 99, float(rb["close"][0]))
    cbad = coin(bb["ticks"])
    chg_b = np.diff(bb["close"])
    mb = float(chg_b.mean())
    seb = float(chg_b.std(ddof=1) / math.sqrt(chg_b.size))
    print(f"    tick p(up) {cbad['p_up']:.6f} z {cbad['z']:+.2f}  |  bar-sample implied "
          f"p(up) {0.5 + mb / (2 * STEP_SIZE * TPB):.6f}, z on the mean change {mb / seb:+.2f}")
    zg = float(chg_s.mean() / (chg_s.std(ddof=1) / math.sqrt(chg_s.size)))
    print(f"    the same bar test on the honest rebuild: {zg:+.2f}")
    ledger.append({"test": "VOID unless p_up=0.501 is caught on the bar sample",
                   "feed": "step_index", "value": mb / seb, "fired": abs(mb / seb) < 3})
    print("    and the sample size a fair-coin test needs to see the feed's own")
    print(f"    measured bias of 0.000266: n* = {0.25 * (1.96 / 0.000266) ** 2:.3g} flips")

    payload["step"] = {"real": {"concentration": mc["share"], "p_up": cn["p_up"],
                                "se": cn["se"], "runs_z": cn["runs_z"],
                                "spread_in_steps": spread_med / step},
                       "sim_concentration": conc, "sim_p_up_z": zs,
                       "ruin_real": ru_real, "ruin_sim": ru_sim, "ruin_past": ru_past,
                       "chi2": c2t, "ks": kk, "control": kc}

    # -------------------------------------------------------- range break -----
    print("\n[6] RANGE BREAK - reproducing `deriving.md`'s variance-ratio table first")
    print("    Three readings of 'ex-break'. Only one of them can produce a number at")
    print("    n=1000, because a thousand break-free minutes has probability 1e-5.")
    rbfeeds = ["range_break_100_index", "range_break_200_index"]
    rbreal, rbpar = {}, {}
    for feed in rbfeeds:
        bars = G.real_bars(feed)
        tk = G.real_ticks(feed)
        d = np.diff(tk["mid"])
        st = float(np.median(np.abs(d[d != 0])))
        cur = vr_curves(bars, st)
        bs = break_stats(bars, st)
        vis = visited_ranges(bars, st)
        rbreal[feed] = {"bars": bars, "ticks": tk, "step": st, "vr": cur, "brk": bs,
                        "visited": vis}
        print(f"\n    {feed}: step {st:g}, {tk['per_sec']:.4f} ticks/s, "
              f"{bs['n_breaks']} breaks in {bars['n']} bars = {bs['minutes_per_break']:.1f} "
              f"min/break, gap CV {bs['gap_cv']:.3f}")
        print(f"      break jump in steps: median {bs['jump_median']:.1f} "
              f"mean {bs['jump_mean']:.1f} sd {bs['jump_sd']:.1f} "
              f"q10/q90/q99 {bs['jump_q'].get(10, 0):.0f}/{bs['jump_q'].get(90, 0):.0f}/"
              f"{bs['jump_q'].get(99, 0):.0f}")
        print(f"      visited range between breaks, in steps: median "
              f"{np.median(vis):.1f}, q90 {np.percentile(vis, 90):.1f}, max {vis.max():.1f} "
              f"(n={vis.size})")
        print(f"      {'n':>6s} " + " ".join(f"{n:>9d}" for n in VR_N))
        for tag in ("all", "splice", "window"):
            print(f"      {tag:>6s} " + " ".join(
                f"{cur[tag].get(n, float('nan')):9.3f}" for n in VR_N))
        print(f"      {'+-SE':>6s} " + " ".join(f"{cur['se'][n]:9.3f}" for n in VR_N))
        print("      window cell counts: " + " ".join(
            f"n={n}:{cur['window'].get(f'{n}_n', 0)}" for n in VR_N))
        print("      break share of variance: " + ", ".join(
            f"n={k}: {v:.3f}" for k, v in cur["break_share"].items()))

    # a free walk with no range at all: the estimator's own control
    print("\n    control - a free +-1 walk with no range and no break:")
    ctlbars = G.bars_from_stream(
        G.gen_step(400_000 * TPB, 1.0, 0.5, 10000.0, np.random.default_rng(5)),
        TPB, 400_000)
    cc = vr_curves(ctlbars, 1.0)
    print(f"      {'n':>6s} " + " ".join(f"{n:>9d}" for n in VR_N))
    for tag in ("all", "splice"):
        print(f"      {tag:>6s} " + " ".join(
            f"{cc[tag].get(n, float('nan')):9.3f}" for n in VR_N))
    ledger.append({"test": "VOID unless the free-walk control reads 1.0 at every n",
                   "feed": "free walk",
                   "value": max(abs(cc["all"][n] - 1.0) for n in VR_N),
                   "fired": max(abs(cc["all"][n] - 1.0) for n in VR_N) > 0.15})

    print("\n[7] RANGE BREAK REBUILT - the band width estimated off the *visited* range,")
    print("    never off the variance ratio, and then the six variance ratios predicted.")
    print("    Two candidate re-range rules, because `deriving.md` publishes neither:")
    print("      edge   - the break point becomes the new range's near edge")
    print("      centre - the new range is centred on the break point")
    for feed in rbfeeds:
        R = rbreal[feed]
        mbt = R["brk"]["minutes_per_break"] * TPB
        pool = R["brk"]["_jump"]
        rbpar[feed] = {"mean_break_ticks": mbt,
                       "target_median": float(np.median(R["visited"]))}
        for anchor in ANCHORS:
            band, got, dks = fit_band(R["visited"], mbt, pool,
                                      float(R["bars"]["close"][0]), R["step"], SEEDS[0],
                                      anchor=anchor)
            rbpar[feed][anchor] = {"band": band, "fit_median": got, "fit_ks_D": dks}
            print(f"    {feed} [{anchor}]: band {band} steps (median visited range "
                  f"{got:.1f} against the feed's {np.median(R['visited']):.1f}, "
                  f"KS D {dks:.3f}); break every {mbt:.0f} ticks; jump resampled from "
                  f"{pool.size} break bars")

    print(f"\n{'feed':22s} {'rule':>7s} {'seed':>10s} {'':>7s} "
          + " ".join(f"{'n=' + str(n):>9s}" for n in VR_N) + f" {'flat max/min':>13s}")
    rbsim, rbnull = {}, {}
    for feed in rbfeeds:
        R = rbreal[feed]
        rbsim[feed] = {}
        rbnull[feed] = {}
        n_bars = min(R["bars"]["n"] * RBMULT, 500_000)
        for anchor in ANCHORS:
            band = rbpar[feed][anchor]["band"]
            runs = []
            for sd in SEEDS:
                bb = sim_rb(n_bars, band, rbpar[feed]["mean_break_ticks"],
                            R["brk"]["_jump"], sd, float(R["bars"]["close"][0]),
                            R["step"], anchor)
                cur = vr_curves(bb, R["step"])
                bs = break_stats(bb, R["step"])
                runs.append({"vr": cur, "brk": bs, "bars": bb})
                allv = [cur["all"][n] for n in VR_N]
                print(f"{feed:22s} {anchor:>7s} {sd:>10d} {'all':>7s} "
                      + " ".join(f"{v:9.3f}" for v in allv)
                      + f" {max(allv) / min(allv):13.3f}", flush=True)
                print(f"{'':22s} {'':>7s} {'':>10s} {'splice':>7s} " + " ".join(
                    f"{cur['splice'][n]:9.3f}" for n in VR_N))
            rbsim[feed][anchor] = runs
            # The sampling distribution of a variance ratio on a jump process is
            # nothing like sqrt(2/k) - the smoke test on data generated by this
            # very model put the true parameters 4.6 "standard errors" away. So
            # the null is built by Monte Carlo at the *feed's own sample size*
            # instead, and the feed is scored against that ensemble.
            null = []
            for j in range(NULL_SEEDS):
                bb = sim_rb(R["bars"]["n"], band, rbpar[feed]["mean_break_ticks"],
                            R["brk"]["_jump"], 7000 + 13 * j, float(R["bars"]["close"][0]),
                            R["step"], anchor)
                null.append(vr_curves(bb, R["step"]))
            rbnull[feed][anchor] = null
            fl = G.spread_across([max(r["vr"]["all"][n] for n in VR_N)
                                  / min(r["vr"]["all"][n] for n in VR_N) for r in runs])
            ledger.append({"test": f"[{anchor}] RB all-bars variance ratio flat (max/min <= 1.35)",
                           "feed": feed, "value": fl["mean"], "fired": fl["mean"] > 1.35})
            for n in VR_N:
                sp = G.spread_across([c["splice"][n] for c in null])
                tgt = R["vr"]["splice"][n]
                z = (tgt - sp["mean"]) / sp["sd"] if sp["sd"] else float("nan")
                ledger.append({
                    "test": f"[{anchor}] RB ex-break variance ratio at n={n} within 3 MC SD",
                    "feed": feed, "value": z, "fired": abs(z) > 3})
            cvs = G.spread_across([r["brk"]["gap_cv"] for r in runs])
            ledger.append({"test": f"[{anchor}] RB break waiting-time CV in 0.85-1.15",
                           "feed": feed, "value": cvs["mean"],
                           "fired": not (0.85 <= cvs["mean"] <= 1.15)})
            lvl = G.spread_across([r["brk"]["n_breaks"] / r["bars"]["n"] for r in runs])
            ledger.append({"test": f"[{anchor}] VOID if more than one bar in ten has a break",
                           "feed": feed, "value": lvl["mean"], "fired": lvl["mean"] > 0.1})
        allr = [R["vr"]["all"][n] for n in VR_N]
        print(f"{feed:22s} {'FEED':>7s} {'':>10s} {'all':>7s} "
              + " ".join(f"{v:9.3f}" for v in allr)
              + f" {max(allr) / min(allr):13.3f}")
        print(f"{'':22s} {'':>7s} {'':>10s} {'splice':>7s} " + " ".join(
            f"{R['vr']['splice'][n]:9.3f}" for n in VR_N))

    print(f"\n    the feed scored against a {NULL_SEEDS}-seed rebuild ensemble at the")
    print("    feed's own sample size: (feed - ensemble mean) / ensemble sd.")
    print(f"{'feed':22s} {'rule':>7s} {'series':>7s} "
          + " ".join(f"{'n=' + str(n):>9s}" for n in VR_N))
    for feed in rbfeeds:
        R = rbreal[feed]
        for anchor in ANCHORS:
            null = rbnull[feed][anchor]
            for series in ("all", "splice"):
                row = []
                for n in VR_N:
                    sp = G.spread_across([c[series][n] for c in null])
                    row.append((R["vr"][series][n] - sp["mean"]) / sp["sd"]
                               if sp["sd"] else float("nan"))
                print(f"{feed:22s} {anchor:>7s} {series:>7s} "
                      + " ".join(f"{v:+9.2f}" for v in row))
    print("\n    and the ensemble's own spread, which is what those z are divided by:")
    print(f"{'feed':22s} {'rule':>7s} {'series':>7s} "
          + " ".join(f"{'n=' + str(n):>9s}" for n in VR_N))
    for feed in rbfeeds:
        for anchor in ANCHORS:
            null = rbnull[feed][anchor]
            for series in ("all", "splice"):
                print(f"{feed:22s} {anchor:>7s} {series:>7s} " + " ".join(
                    f"{G.spread_across([c[series][n] for c in null])['sd']:9.4f}"
                    for n in VR_N))

    print("\n[8] RANGE BREAK - the levels the flatness is made of, so it cannot be degenerate")
    print(f"{'feed':24s} {'':>8s} {'min/break':>10s} {'gap CV':>8s} {'ex-brk 1m sd':>13s} "
          f"{'jump median':>12s} {'bars w/ break':>14s}")
    for feed in rbfeeds:
        R = rbreal[feed]
        chg = np.diff(R["bars"]["close"])
        brk = break_bars(R["bars"], R["step"])[1:]
        print(f"{feed:24s} {'feed':>8s} {R['brk']['minutes_per_break']:10.1f} "
              f"{R['brk']['gap_cv']:8.3f} {chg[~brk].std(ddof=1) / R['step']:13.2f} "
              f"{R['brk']['jump_median']:12.1f} "
              f"{R['brk']['n_breaks'] / R['bars']['n']:14.5f}")
        for r2 in rbsim[feed][MAIN_ANCHOR][:1]:
            ch2 = np.diff(r2["bars"]["close"])
            b2 = break_bars(r2["bars"], R["step"])[1:]
            print(f"{'':24s} {'rebuilt':>8s} {r2['brk']['minutes_per_break']:10.1f} "
                  f"{r2['brk']['gap_cv']:8.3f} {ch2[~b2].std(ddof=1) / R['step']:13.2f} "
                  f"{r2['brk']['jump_median']:12.1f} "
                  f"{r2['brk']['n_breaks'] / r2['bars']['n']:14.5f}")

    r100 = rbreal["range_break_100_index"]["brk"]["minutes_per_break"]
    r200 = rbreal["range_break_200_index"]["brk"]["minutes_per_break"]
    s100 = G.spread_across([r2["brk"]["minutes_per_break"]
                            for r2 in rbsim["range_break_100_index"][MAIN_ANCHOR]])["mean"]
    s200 = G.spread_across([r2["brk"]["minutes_per_break"]
                            for r2 in rbsim["range_break_200_index"][MAIN_ANCHOR]])["mean"]
    print(f"\n    RB200/RB100 break interval: feed {r200 / r100:.3f}  rebuilt {s200 / s100:.3f}"
          f"  documented 2.000, generators.md 2.066 [1.86, 2.30]")
    ledger.append({"test": "RB rate ratio 2.066 +- 0.30", "feed": "RB200/RB100",
                   "value": s200 / s100, "fired": abs(s200 / s100 - 2.066) > 0.30})

    print("\n[9] RANGE BREAK - the distributions, real against rebuilt")
    print(f"{'feed':24s} {'what':>16s} {'n real':>8s} {'n sim':>9s} {'KS D':>9s} "
          f"{'D crit':>8s} {'p':>8s} {'chi2 p':>8s} {'n*':>12s}")
    for feed in rbfeeds:
        R = rbreal[feed]
        S = rbsim[feed][MAIN_ANCHOR][0]
        exr = np.diff(R["bars"]["close"])[~break_bars(R["bars"], R["step"])[1:]] / R["step"]
        exs = np.diff(S["bars"]["close"])[~break_bars(S["bars"], R["step"])[1:]] / R["step"]
        for what, a, b in (("1m change", np.diff(R["bars"]["close"]) / R["step"],
                            np.diff(S["bars"]["close"]) / R["step"]),
                           ("ex-break 1m", exr, exs),
                           ("break gaps", np.diff(R["brk"]["_idx"]).astype(float),
                            np.diff(S["brk"]["_idx"]).astype(float)),
                           ("visited range", R["visited"], visited_ranges(S["bars"], R["step"]))):
            if a.size < 30 or b.size < 30:
                continue
            k = G.ks2(a, b, rng=rng)
            c2t = G.chi2_hist(a, b, nbin=30)
            print(f"{feed:24s} {what:>16s} {a.size:8d} {b.size:9d} {k['D']:9.5f} "
                  f"{k['D_crit_05']:8.5f} {k['p']:8.4f} {c2t['p']:8.4f} "
                  f"{G.nstar(k['D']):12.3g}")
            payload.setdefault("rb_ks", {}).setdefault(feed, {})[what] = {"ks": k, "chi2": c2t}
            ledger.append({"test": f"RB {what}: KS does not reject", "feed": feed,
                           "value": k["p"], "fired": k["reject"]})

    payload["rangebreak"] = json.loads(json.dumps(
        {f: {"params": rbpar[f],
             "real_vr": {k: v for k, v in rbreal[f]["vr"].items() if k != "break_share"},
             "real_break": {k: v for k, v in rbreal[f]["brk"].items() if not k.startswith("_")},
             "sim_vr_all": {a: [{n: r2["vr"]["all"][n] for n in VR_N} for r2 in rbsim[f][a]]
                            for a in ANCHORS},
             "sim_vr_splice": {a: [{n: r2["vr"]["splice"][n] for n in VR_N} for r2 in rbsim[f][a]]
                               for a in ANCHORS}}
         for f in rbfeeds}, default=float))

    print("\n[10] THE FAILURE LEDGER")
    by: dict[str, list] = {}
    for e in ledger:
        by.setdefault(e["test"], []).append(e)
    print(f"{'condition':62s} {'cells':>6s} {'fired':>6s} {'worst cell':>30s}")
    nf = 0
    for name, es in by.items():
        f2 = [e for e in es if e["fired"]]
        nf += len(f2)
        worst = max(es, key=lambda e: abs(e.get("value") or 0))
        print(f"{name:62s} {len(es):6d} {len(f2):6d} "
              f"{worst['feed'] + ' ' + format(worst['value'], '.5g'):>30s}")
    print(f"\n    {len(ledger)} pre-registered comparisons, {nf} fired.")
    payload["ledger"] = ledger

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        json.dump(json.loads(json.dumps(payload, default=float)), fh, indent=1)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
